#! /bin/sh

# Resolution hack for now
#xrandr --output DP-0 --mode 3440x1440 --rate 74.98

###########################################
##  Auto Starts
###########################################
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
bash ~/.config/polybar/launch.sh &

# Wallpaper
feh --randomize --bg-fill ~/Pictures/Backgrounds/Dracula/*

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

bspc config focused_border_color "#6272A4"
bspc config normal_border_color  "#44475A"
bspc config active_border_color  "#6272A4"
bspc config presel_feedback_color "#44475A"


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme	 alternate

bspc config ignore_ewmh_focus true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Floating
bspc rule -a Xarchiver state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Yad state=floating
bspc rule -a Blueman-manager state=floating

# Push it!
bspc rule -a transmission-gtk:transmission-gtk -o desktop='^9'
bspc rule -a Spotify desktop='^5' follow=off
bspc rule -a Discord desktop='^7'

# Auto Start
bspc desktop -f ^9
lxpolkit &
picom --config ~/.config/bspwm/picom.conf &
#picom --animations -b &
#picom --config ~/.config/bspwm/picom2.conf &
xmodmap ~/.Xmodmap
bspc desktop -f ^1
