#! /bin/sh

# Resolution hack for now
xrandr --output DP-0 --mode 3440x1440 --rate 74.98

#NVidia Tweak
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"

###########################################
##  Auto Starts
###########################################
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Polybar
bash ~/.config/polybar/launch.sh &

# Dunst
/usr/bin/dunst &

# Cursor stuff
xsetroot -cursor_name left_ptr

# Mount usb drives
udiskie &

# Wallpaper
feh --randomize --bg-fill /home/lobster/Pictures/Backgrounds/*

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

#bspc config focused_border_color "#81B6C6"
bspc config focused_border_color "#4C566A"
bspc config normal_border_color  "#3B4252"
bspc config active_border_color  "#81B6C6"
bspc config presel_feedback_color "#3B4252"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme	 alternate

bspc config ignore_ewmh_focus true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Floating
bspc rule -a Xarchiver state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Yad state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a nwg-look state=floating

# Push it!
bspc rule -a transmission-gtk:transmission-gtk -o desktop='^8'
bspc rule -a Spotify desktop='^5' follow=off
bspc rule -a steam desktop='^6' 
bspc rule -a Discord desktop='^7'

# Auto Start
bspc desktop -f ^9
lxpolkit &
picom --config ~/.config/bspwm/picom.conf &
#picom --config ~/.config/bspwm/picom_animations.conf &
bspc desktop -f ^1
